### ISSUE TITLE
KeyError: (8, 0) when opening a Midi file, probably an error in the file that is not handled?!

### ISSUE THREAD

**Issue by schtibe** [olemb/mido#105]
I try to open a MIDI file that I received from a customer, and it ends with following error:

```
----> 1 mido.MidiFile("/tmp/PianoFeelThisMoment.mid")

~/.pyenv/versions/3.5.3/envs/energyday/lib/python3.5/site-packages/mido/midifiles/midifiles.py in __init__(self, filename, file, type, ticks_per_beat, charset, debug)
    300         elif self.filename is not None:
    301             with io.open(filename, 'rb') as file:
--> 302                 self._load(file)
    303 
    304     def add_track(self, name=None):

~/.pyenv/versions/3.5.3/envs/energyday/lib/python3.5/site-packages/mido/midifiles/midifiles.py in _load(self, infile)
    335                     _dbg('Track {}:'.format(i))
    336 
--> 337                 self.tracks.append(read_track(infile, debug=self.debug))
    338                 # Todo: used to ignore EOFError. I hope things still work.
    339 

~/.pyenv/versions/3.5.3/envs/energyday/lib/python3.5/site-packages/mido/midifiles/midifiles.py in read_track(infile, debug)
    209 
    210         if status_byte == 0xff:
--> 211             msg = read_meta_message(infile, delta)
    212         elif status_byte in [0xf0, 0xf7]:
    213             # Todo: I'm not quite clear on the difference between

~/.pyenv/versions/3.5.3/envs/energyday/lib/python3.5/site-packages/mido/midifiles/midifiles.py in read_meta_message(infile, delta)
    163     length = read_variable_int(infile)
    164     data = read_bytes(infile, length)
--> 165     return build_meta_message(type, data, delta)
    166 
    167 

~/.pyenv/versions/3.5.3/envs/energyday/lib/python3.5/site-packages/mido/midifiles/meta.py in build_meta_message(type, data, delta)
    440 
    441         # This adds attributes to msg:
--> 442         spec.decode(msg, data)
    443 
    444         return msg

~/.pyenv/versions/3.5.3/envs/energyday/lib/python3.5/site-packages/mido/midifiles/meta.py in decode(self, message, data)
    383         key = signed('byte', data[0])
    384         mode = data[1]
--> 385         message.key = _key_signature_decode[(key, mode)]
    386 
    387     def encode(self, message):

KeyError: (8, 0)

```

I looked at the code of the line that fails, and there's clearly some sort of note mapping going on. I suspect that (8, 0) should not be in the file in the first place, but my understanding of MIDI is limited... Since I have no control over the creation of the file, I'd appreciate some sort of error handling there, but I can't asses if this is even remotely sensible.

I'm using mido 1.2.7 on python 3.5.3. I'm not sure yet if I'm allowed to give you the file, sorry for that :(

**Comment by cjappl** [comment]
Can you give the snippet of the file that the code is failing on? It'd be hard to dig in without a little more information on data it's failing on.

**Comment by schtibe** [comment]
I checked, and I can even give you the whole file: 
[track.zip](https://github.com/olemb/mido/files/1179710/track.zip)

**Comment by olemb** [comment]
This is due to a key signature message with the invalid value `(8, 0)`. As you can see it is not included in the conversion table: https://github.com/olemb/mido/blob/f23a97427a9c36a1afea4ab4d67338f4741b9edb/mido/midifiles/meta.py#L27

This matches the list of valid values: http://www.recordingblogs.com/sa/Wiki/topic/MIDI-Key-Signature-meta-message

The first byte is the number of sharps/flats and the second byte is major/minor which means `(8, 0)` is a major key with 8 sharps. This doesn't make sense as there are only 7 white keys in a scale, so I don't know what this is supposed to mean. Possible it's some kind of custom value. It could also be caused by a bug.

I've come across this before but I haven't found a good solution yet. (Perhaps it was a mistake to convert these to strings. It could have been better to leave them as numbers and leave the conversion up to the user but it's too late to change it now.)

If you don't need key signatures you can remove the handler:

```
from mido import MidiFile
import mido.midifiles.meta as meta

del meta._META_SPECS[0x59]
del meta._META_SPEC_BY_TYPE['key_signature']

mid = MidiFile('PianoFeelThisMoment.mid')
```

This is not officially supported so there's no guarantee that it will work in the future.

Alternatively you could write your own handler: 
https://mido.readthedocs.io/en/latest/meta_message_types.html#implementing-new-meta-messages
(The easiest way is to copy `MetaSpec_key_signature` in `mido/midifiles/meta.py` and modify it.)

I would be best if Mido could somehow handle this without crashing. Let me know if you have any ideas for how these messages could be handled.

**Comment by olemb** [comment]
I just discovered a bug in the `UnknownMetaMessage` class. The example above will work but it looks like printing an unknown message or writing it to a file will crash due to a missing `data` attribute. I'll need to look into this.

**Comment by olemb** [comment]
I have fixed the bug in my master branch.

**Comment by cjappl** [comment]
Maybe the temporary solution is to raise something like `KeySignatureError('invalid number of sharps!)`?

That'd at least be a more clear error for people in the future. Same could be applied for >7 flats as well.

**Comment by olemb** [comment]
That's a good idea!

Should we make it a subclass of `MidiParseError`? I think that would make sense.

**Comment by cjappl** [comment]
Yeah, I think that makes sense for sure! I'll see if I can put a PR together later on today

**Comment by cjappl** [comment]
See #117

**Comment by cjappl** [comment]
I think this can be closed

**Comment by olemb** [comment]
I agree.

It would be nice to have a way to read a file even if it contains invalid messages but that sounds like a separate issue.
