### ISSUE TITLE
Synchronizing MIDI to clock

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [olemb/mido#153]
I need to synchronize my MIDI playback to a video.

I have my video playing back synchronized with the system clock.  It plays back the correct frame at exactly the correct time.

Is it going to be difficult for me to do this using MIDI with mido?

The current timing scheme of sleeping using the time between messages works very well by itself, but doesn't do well when it needs to be synchronized.

I'm still a MIDI rookie so I'm learning as quickly as I can but am still not fully educated clearly. Just looking for some guidance on whether this is beyond the scope of mido and I should consider something else.... or if it's like tempo was, a simple change.

Any help is greatly appreciated.

**Comment by MikeTheWatchGuy** [comment]
For the time being, I synced my MIDI to the system clock to error correct for the amount of time spent doing other things than the MIDI. 

If the MIDI loop gets delayed then don't want to have the delay affect the playback.  I did this by timing the amount of time between the reads from the midifile (where the sleep is located in the mido code).

**Comment by almostimplemented** [comment]
I also encountered the need for this functionality -- I wanted to synchronize MIDI playback with a `sounddevice.Stream`. I achieved this by duplicating the logic in `mido.MidiFile.play` to use `sounddevice.Stream.time` instead of `time.time()`.

Would Mido be interested in adding this as an optional argument to `mido.MidiFile.play`? I would propose a simple solution like this:
```
    def play(self, meta_messages=False, now=time.time):
        """Play back all tracks.
...
        To synchronize to a different clock source, replace
        now with a zero argument function that returns the 
        current time in seconds.
        """
        start_time = now()
        input_time = 0.0

        for msg in self:
            input_time += msg.time

            playback_time = now() - start_time
            duration_to_next_event = input_time - playback_time

            if duration_to_next_event > 0.0:
                time.sleep(duration_to_next_event)
...
```
Then my problem would be solved via `mid.play(now=lambda: stream.time)`.

I would be honored to open a PR if this is desirable! 

I do realize that `mido.MidiFile.play` is quite a simple function; it was not really an issue to copy and modify. But this seems like a generally useful bit of behavior for music programming.
