### ISSUE TITLE
rtmidi backend 

### ISSUE THREAD

**Issue by Eirikur** [olemb/mido#32]
I'm getting this on a fresh pip install:

 'Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mido/backends/rtmidi.py", line 9,
 in <module>
    import rtmidi
ImportError: No module named rtmidi

This is in the import of the module where it tries a recursive import of itself.   I think that's been prevented in Python 2.76 and Python 3.4.  I couldn't get it to work in either version.
I used to do things like this, myself, but I think it needs to change.

My best,

Eirikur

**Comment by olemb** [comment]
Since the 'import rtmidi' is inside a package it will not do a recursive import, but instead try to import a module at the top level called 'rtmidi'. This module is provided by the python-rtmidi package which can be installed with:

    pip3 install --user --pre python-rtmidi

(Using pip or pip3. The --user is optional.)

I will add a better error message ('required package python-rtmidi missing') to make this less confusing.

**Comment by olemb** [comment]
I've removed the custom code here so you can see the actual import error. This should be less confusing.
