### ISSUE TITLE
Converting a message to bytes and parsing it throws away time information

### ISSUE THREAD

**Issue by carlthome** [olemb/mido#94]
```python
In [1]: import mido as md

In [2]: midi = md.MidiFile('test.mid')

In [3]: midi_message = midi.tracks[0][0]

In [4]: midi_message
Out[4]: <message note_on channel=0 note=60 velocity=127 time=2899>

In [5]: md.Message.from_bytes(midi_message.bin())
Out[5]: <message note_on channel=0 note=60 velocity=127 time=0>

In [6]: md.Message.from_bytes(midi_message.bytes())
Out[6]: <message note_on channel=0 note=60 velocity=127 time=0>
```

This might be intended behaviour but I expected converting a Mido Message object to bytes and then parsing it per the documentation would give the exact same message. Am I missing something obvious or is this a bug?

**Comment by olemb** [comment]
The `time` attribute is something I added for convenience. Since MIDI is a realtime protocol there is no time information in messages, which means that the `time` attribute must be discarded when encoding to bytes. If you want to keep the time you need to store it somewhere else. For example, in MIDI files there is a time stamp before each message.

I'm sorry for the confusion. It would probably have been cleaner to leave out the time so the message object and the binary representation contained the same information. This would make MIDI files inconvenient though.

**Comment by carlthome** [comment]
Thanks for clarifying! That sounds very reasonable.

In order to keep Mido's time value I started using your string representation instead of the MIDI bytes, as I don't really need to keep message lengths down anyway.

E.g. 

```python
# Passing Mido messages as MIDI bytes discards Mido's time attribute.
data = b''.join(m.bin() for m in messages)
messages = md.parse_all(data)

# Passing Mido messages as strings maintains Mido's time attribute.
data = "\n".join(str(m) for m in messages).encode()
messages = [md.Message.from_str(x) for x in data.decode().splitlines()]
```

**Comment by carlthome** [comment]
Maybe defer to RTFM but it could be nice if a mido.Message conversion lets the user know if any self.__dict__ values will be discarded with a `warnings.warn` (i.e. I'm stupid :koala: ).

**Comment by olemb** [comment]
I think this should be a RTFM, as a warning would create noise and cause confusion for common cases. For example, calling `port.send(msg)` would give you a warning.

That said, the docs and doc strings should probably be updated with a note about this.

I'm glad the string format worked out for you.
